name: build

on:
    pull_request: ~
    push:
        branches:
            - "master"
    schedule:
        - cron: 5 8 * * 3

env:
    KRAKEN_API_KEY: "${{ secrets.KrakenApiKey }}"
    KRAKEN_API_SECRET: "${{ secrets.KrakenApiSecret }}"

jobs:
    checks:
        name: PHP ${{ matrix.php-version }}
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-version:
                    - '7.3'
                    - '7.4'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@master
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring
            -   name: Install Composer dependencies
                run: composer update --no-progress --no-suggest --prefer-dist --no-interaction
            -   name: Validate composer
                run: composer validate --strict
            -   name: Check composer normalized
                run: composer normalize --dry-run
            -   name: Check style
                run: composer check-style
            -   name: Static analysis
                run: composer analyse
            -   name: Run phpunit
                run: composer phpunit
